dist: trusty

language: go

go:
  - 1.7.x
  - 1.8.x

services:
  - mongo
  - mysql

env:
  - "PCT_TEST_MYSQL_DSN=\"root:travis@tcp(localhost:3306)/?parseTime=true\""

addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.percona.com/apt precise testing'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x8507EFA5'
    packages:
      - percona-toolkit

install:
  - go get -u github.com/Masterminds/glide
  - glide install

before_script:
  - mongo --eval 'db.setProfilingLevel(2)'

script:
  - test/runner.sh

notifications:
  email:
    on_success: change
    on_failure: change
